name: Ping Streamlit App

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:     # Allows manual trigger from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: |
          echo "Pinging Streamlit app..."
          curl -s -o /dev/null -w "%{http_code}" -L https://insta-insights.streamlit.app/
