name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to MyStreamlitApp
        run: |
          wget -qO- "https://insta-insights.streamlit.app/?ping=$(date +%s)" > /dev/null
