name: Ping Streamlit App

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App with Logging
        run: |
          echo "Sending request to Streamlit app..."
          curl -s -L -w "HTTP Status: %{http_code}\n" https://insta-insights.streamlit.app/ -o response.txt
          echo "Response Body:"
          cat response.txt
