name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to MyStreamlitApp
        run: curl -s -o /dev/null -w "%{http_code}\n" https://insta-insights.streamlit.app/
